#!/bin/bash

# Check if the PYFILE environment variable is set or not
if [ -z "$PYFILE" ]; then
    echo "Error: env variable not set."
    exit 1
fi

# Check if the specified Python file exists
if [ ! -f "$PYFILE" ]; then
    echo "Error: Python file '$PYFILE' not found."
    exit 1
fi

# Run the code
python3 "$PYFILE"
